# Generated by Django 2.2.5 on 2019-09-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('indice', models.CharField(max_length=10)),
                ('date_update', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ManyToManyField(to='search.products')),
                ('id_save_product', models.ManyToManyField(related_name='product_replace', to='search.products')),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.ManyToManyField(to='search.products')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.ManyToManyField(to='search.products')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
