# Generated by Django 2.2.5 on 2019-09-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('indice', models.CharField(max_length=10)),
                ('date_update', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('main_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Main_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.ManyToManyField(to='search.Product')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.ManyToManyField(to='search.Product')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
