# Generated by Django 2.2.5 on 2019-09-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_categories_ingredients_product_save_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_save',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='product_save',
            name='id_save_product',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='product_save',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
